### ISSUE TITLE
misleading chmod entry

### ISSUE THREAD

**Issue by MoccoCoffee** [kluntze/cfetch#19]
good evening. i took a glance at your program. it's good, actually, but i've found one little bug while installing it using your manual. somehow, the makefile refers to "/bin" instead of "/usr/bin", in where the program was copied to. however, manually typing chmod with entering "/usr/bin/cfetch" as the target file does work, so the only problem is on the makefile. i know how to solve that, but not sure if i can do that in a makefile language...

p.s here's a screenshot
![image](https://user-images.githubusercontent.com/52582484/107126220-8dae8880-68bf-11eb-9bfd-181f818d0a65.png)

**Comment by kluntze** [comment]
Hello, thanks for the help. I fixed the Makefile, it should work now :)
